/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPorAggregator,
  IPorAggregatorInterface,
} from "../../../../contracts/ops/CircuitBreaker.sol/IPorAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "reserveId",
        type: "bytes32",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "bool",
        name: "ok",
        type: "bool",
      },
      {
        internalType: "uint64",
        name: "asOf",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPorAggregator__factory {
  static readonly abi = _abi;
  static createInterface(): IPorAggregatorInterface {
    return new Interface(_abi) as IPorAggregatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPorAggregator {
    return new Contract(address, _abi, runner) as unknown as IPorAggregator;
  }
}
