/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReserveQuorumView,
  IReserveQuorumViewInterface,
} from "../../../../contracts/ccip/PorBroadcaster.sol/IReserveQuorumView";

const _abi = [
  {
    inputs: [],
    name: "latestSealed",
    outputs: [
      {
        internalType: "uint64",
        name: "epoch",
        type: "uint64",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "totalAssets1e18",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalLiabilities1e18",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "cash1e18",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tBills1e18",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "repos1e18",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "other1e18",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "documentsCid",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "asOf",
            type: "uint64",
          },
        ],
        internalType: "struct IReserveQuorumView.Snapshot",
        name: "s",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReserveQuorumView__factory {
  static readonly abi = _abi;
  static createInterface(): IReserveQuorumViewInterface {
    return new Interface(_abi) as IReserveQuorumViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReserveQuorumView {
    return new Contract(address, _abi, runner) as unknown as IReserveQuorumView;
  }
}
