/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TravelRuleMockInterface extends Interface {
  getFunction(nameOrSignature: "hasPermit" | "ok" | "set"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasPermit",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ok", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "hasPermit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ok", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
}

export interface TravelRuleMock extends BaseContract {
  connect(runner?: ContractRunner | null): TravelRuleMock;
  waitForDeployment(): Promise<this>;

  interface: TravelRuleMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasPermit: TypedContractMethod<
    [f: AddressLike, t: AddressLike, a: BigNumberish, ttl: BigNumberish],
    [boolean],
    "view"
  >;

  ok: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  set: TypedContractMethod<
    [
      f: AddressLike,
      t: AddressLike,
      amt: BigNumberish,
      ttl: BigNumberish,
      yes: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasPermit"
  ): TypedContractMethod<
    [f: AddressLike, t: AddressLike, a: BigNumberish, ttl: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ok"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "set"
  ): TypedContractMethod<
    [
      f: AddressLike,
      t: AddressLike,
      amt: BigNumberish,
      ttl: BigNumberish,
      yes: boolean
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
