/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ComplianceModuleRBAC__factory } from "./ComplianceModuleRBAC__factory";
export { IComplianceGate__factory } from "./IComplianceGate__factory";
export { IKYC__factory } from "./IKYC__factory";
export { ISanctionsView__factory } from "./ISanctionsView__factory";
