/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ComplianceModuleRBACInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "assetAllowed"
      | "check"
      | "kyc"
      | "sanctions"
      | "setAssetAllowed"
      | "setKYC"
      | "setSanctions"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "AssetAllowed"
      | "KYCSet"
      | "SanctionsSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "check",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "kyc", values?: undefined): string;
  encodeFunctionData(functionFragment: "sanctions", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAssetAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setKYC", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setSanctions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kyc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sanctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssetAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSanctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetAllowedEvent {
  export type InputTuple = [asset: AddressLike, allowed: boolean];
  export type OutputTuple = [asset: string, allowed: boolean];
  export interface OutputObject {
    asset: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCSetEvent {
  export type InputTuple = [kyc: AddressLike];
  export type OutputTuple = [kyc: string];
  export interface OutputObject {
    kyc: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SanctionsSetEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceModuleRBAC extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceModuleRBAC;
  waitForDeployment(): Promise<this>;

  interface: ComplianceModuleRBACInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  assetAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  check: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      asset: AddressLike,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;

  kyc: TypedContractMethod<[], [string], "view">;

  sanctions: TypedContractMethod<[], [string], "view">;

  setAssetAllowed: TypedContractMethod<
    [asset: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setKYC: TypedContractMethod<[k: AddressLike], [void], "nonpayable">;

  setSanctions: TypedContractMethod<[s: AddressLike], [void], "nonpayable">;

  transferAdmin: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      asset: AddressLike,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "kyc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sanctions"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAssetAllowed"
  ): TypedContractMethod<
    [asset: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKYC"
  ): TypedContractMethod<[k: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSanctions"
  ): TypedContractMethod<[s: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "AssetAllowed"
  ): TypedContractEvent<
    AssetAllowedEvent.InputTuple,
    AssetAllowedEvent.OutputTuple,
    AssetAllowedEvent.OutputObject
  >;
  getEvent(
    key: "KYCSet"
  ): TypedContractEvent<
    KYCSetEvent.InputTuple,
    KYCSetEvent.OutputTuple,
    KYCSetEvent.OutputObject
  >;
  getEvent(
    key: "SanctionsSet"
  ): TypedContractEvent<
    SanctionsSetEvent.InputTuple,
    SanctionsSetEvent.OutputTuple,
    SanctionsSetEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "AssetAllowed(address,bool)": TypedContractEvent<
      AssetAllowedEvent.InputTuple,
      AssetAllowedEvent.OutputTuple,
      AssetAllowedEvent.OutputObject
    >;
    AssetAllowed: TypedContractEvent<
      AssetAllowedEvent.InputTuple,
      AssetAllowedEvent.OutputTuple,
      AssetAllowedEvent.OutputObject
    >;

    "KYCSet(address)": TypedContractEvent<
      KYCSetEvent.InputTuple,
      KYCSetEvent.OutputTuple,
      KYCSetEvent.OutputObject
    >;
    KYCSet: TypedContractEvent<
      KYCSetEvent.InputTuple,
      KYCSetEvent.OutputTuple,
      KYCSetEvent.OutputObject
    >;

    "SanctionsSet(address)": TypedContractEvent<
      SanctionsSetEvent.InputTuple,
      SanctionsSetEvent.OutputTuple,
      SanctionsSetEvent.OutputObject
    >;
    SanctionsSet: TypedContractEvent<
      SanctionsSetEvent.InputTuple,
      SanctionsSetEvent.OutputTuple,
      SanctionsSetEvent.OutputObject
    >;
  };
}
