/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ComplianceModuleRBAC } from "./ComplianceModuleRBAC";
export type { IComplianceGate } from "./IComplianceGate";
export type { IKYC } from "./IKYC";
export type { ISanctionsView } from "./ISanctionsView";
