/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface Iso20022BridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "bind"
      | "bindings"
      | "emitGPIStatus"
      | "emitGPITracker"
      | "emitMessage"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "GPIPaymentStatusUpdate"
      | "GPITrackerUpdate"
      | "IsoBound"
      | "IsoEvent"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bind",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "bindings", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "emitGPIStatus",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emitGPITracker",
    values: [BytesLike, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emitMessage",
    values: [BytesLike, BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bind", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bindings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emitGPIStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitGPITracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GPIPaymentStatusUpdateEvent {
  export type InputTuple = [
    id: BytesLike,
    uetr: BytesLike,
    status: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    uetr: string,
    status: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: string;
    uetr: string;
    status: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GPITrackerUpdateEvent {
  export type InputTuple = [
    id: BytesLike,
    uetr: BytesLike,
    trackerEventCode: string,
    eventData: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    uetr: string,
    trackerEventCode: string,
    eventData: string
  ];
  export interface OutputObject {
    id: string;
    uetr: string;
    trackerEventCode: string;
    eventData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IsoBoundEvent {
  export type InputTuple = [
    id: BytesLike,
    uetr: BytesLike,
    payloadHash: BytesLike,
    e2eIdHash: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    uetr: string,
    payloadHash: string,
    e2eIdHash: string
  ];
  export interface OutputObject {
    id: string;
    uetr: string;
    payloadHash: string;
    e2eIdHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IsoEventEvent {
  export type InputTuple = [
    id: BytesLike,
    uetr: BytesLike,
    messageType: string,
    payloadHash: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    uetr: string,
    messageType: string,
    payloadHash: string
  ];
  export interface OutputObject {
    id: string;
    uetr: string;
    messageType: string;
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Iso20022Bridge extends BaseContract {
  connect(runner?: ContractRunner | null): Iso20022Bridge;
  waitForDeployment(): Promise<this>;

  interface: Iso20022BridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  bind: TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      payloadHash: BytesLike,
      e2eIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  bindings: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        uetr: string;
        payloadHash: string;
        e2eIdHash: string;
        boundAt: bigint;
      }
    ],
    "view"
  >;

  emitGPIStatus: TypedContractMethod<
    [id: BytesLike, uetr: BytesLike, status: string],
    [void],
    "nonpayable"
  >;

  emitGPITracker: TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      trackerEventCode: string,
      eventData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  emitMessage: TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      messageType: string,
      payloadHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bind"
  ): TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      payloadHash: BytesLike,
      e2eIdHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bindings"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        uetr: string;
        payloadHash: string;
        e2eIdHash: string;
        boundAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emitGPIStatus"
  ): TypedContractMethod<
    [id: BytesLike, uetr: BytesLike, status: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitGPITracker"
  ): TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      trackerEventCode: string,
      eventData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitMessage"
  ): TypedContractMethod<
    [
      id: BytesLike,
      uetr: BytesLike,
      messageType: string,
      payloadHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "GPIPaymentStatusUpdate"
  ): TypedContractEvent<
    GPIPaymentStatusUpdateEvent.InputTuple,
    GPIPaymentStatusUpdateEvent.OutputTuple,
    GPIPaymentStatusUpdateEvent.OutputObject
  >;
  getEvent(
    key: "GPITrackerUpdate"
  ): TypedContractEvent<
    GPITrackerUpdateEvent.InputTuple,
    GPITrackerUpdateEvent.OutputTuple,
    GPITrackerUpdateEvent.OutputObject
  >;
  getEvent(
    key: "IsoBound"
  ): TypedContractEvent<
    IsoBoundEvent.InputTuple,
    IsoBoundEvent.OutputTuple,
    IsoBoundEvent.OutputObject
  >;
  getEvent(
    key: "IsoEvent"
  ): TypedContractEvent<
    IsoEventEvent.InputTuple,
    IsoEventEvent.OutputTuple,
    IsoEventEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "GPIPaymentStatusUpdate(bytes32,bytes16,string,uint256)": TypedContractEvent<
      GPIPaymentStatusUpdateEvent.InputTuple,
      GPIPaymentStatusUpdateEvent.OutputTuple,
      GPIPaymentStatusUpdateEvent.OutputObject
    >;
    GPIPaymentStatusUpdate: TypedContractEvent<
      GPIPaymentStatusUpdateEvent.InputTuple,
      GPIPaymentStatusUpdateEvent.OutputTuple,
      GPIPaymentStatusUpdateEvent.OutputObject
    >;

    "GPITrackerUpdate(bytes32,bytes16,string,bytes32)": TypedContractEvent<
      GPITrackerUpdateEvent.InputTuple,
      GPITrackerUpdateEvent.OutputTuple,
      GPITrackerUpdateEvent.OutputObject
    >;
    GPITrackerUpdate: TypedContractEvent<
      GPITrackerUpdateEvent.InputTuple,
      GPITrackerUpdateEvent.OutputTuple,
      GPITrackerUpdateEvent.OutputObject
    >;

    "IsoBound(bytes32,bytes16,bytes32,bytes32)": TypedContractEvent<
      IsoBoundEvent.InputTuple,
      IsoBoundEvent.OutputTuple,
      IsoBoundEvent.OutputObject
    >;
    IsoBound: TypedContractEvent<
      IsoBoundEvent.InputTuple,
      IsoBoundEvent.OutputTuple,
      IsoBoundEvent.OutputObject
    >;

    "IsoEvent(bytes32,bytes16,string,bytes32)": TypedContractEvent<
      IsoEventEvent.InputTuple,
      IsoEventEvent.OutputTuple,
      IsoEventEvent.OutputObject
    >;
    IsoEvent: TypedContractEvent<
      IsoEventEvent.InputTuple,
      IsoEventEvent.OutputTuple,
      IsoEventEvent.OutputObject
    >;
  };
}
