/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAttestationOracle {
  export type ReserveReportStruct = {
    reserveId: BytesLike;
    timestamp: BigNumberish;
    totalLiabilities: BigNumberish;
    totalReserves: BigNumberish;
    uri: string;
    auditorSig: BytesLike;
  };

  export type ReserveReportStructOutput = [
    reserveId: string,
    timestamp: bigint,
    totalLiabilities: bigint,
    totalReserves: bigint,
    uri: string,
    auditorSig: string
  ] & {
    reserveId: string;
    timestamp: bigint;
    totalLiabilities: bigint;
    totalReserves: bigint;
    uri: string;
    auditorSig: string;
  };
}

export interface IAttestationOracleInterface extends Interface {
  getFunction(nameOrSignature: "hasQuorum" | "latest"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hasQuorum",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "latest", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "hasQuorum", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latest", data: BytesLike): Result;
}

export interface IAttestationOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IAttestationOracle;
  waitForDeployment(): Promise<this>;

  interface: IAttestationOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasQuorum: TypedContractMethod<[reserveId: BytesLike], [boolean], "view">;

  latest: TypedContractMethod<
    [reserveId: BytesLike],
    [
      [IAttestationOracle.ReserveReportStructOutput, boolean] & {
        ok: IAttestationOracle.ReserveReportStructOutput;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasQuorum"
  ): TypedContractMethod<[reserveId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "latest"
  ): TypedContractMethod<
    [reserveId: BytesLike],
    [
      [IAttestationOracle.ReserveReportStructOutput, boolean] & {
        ok: IAttestationOracle.ReserveReportStructOutput;
        exists: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
