/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IProofOfReservesInterface extends Interface {
  getFunction(nameOrSignature: "checkMint" | "checkRedeem"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkMint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRedeem",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "checkMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkRedeem",
    data: BytesLike
  ): Result;
}

export interface IProofOfReserves extends BaseContract {
  connect(runner?: ContractRunner | null): IProofOfReserves;
  waitForDeployment(): Promise<this>;

  interface: IProofOfReservesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkMint: TypedContractMethod<
    [reserveId: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  checkRedeem: TypedContractMethod<
    [reserveId: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkMint"
  ): TypedContractMethod<
    [reserveId: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkRedeem"
  ): TypedContractMethod<
    [reserveId: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  filters: {};
}
