/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngine,
  IPolicyEngineInterface,
} from "../../../../contracts/token/InstitutionalEMTUpgradeable.sol/IPolicyEngine";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "address",
            name: "operator",
            type: "address",
          },
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct Types.TransferContext",
        name: "ctx",
        type: "tuple",
      },
    ],
    name: "checkTransfer",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPolicyEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineInterface {
    return new Interface(_abi) as IPolicyEngineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngine {
    return new Contract(address, _abi, runner) as unknown as IPolicyEngine;
  }
}
