/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAny2EVMMessageReceiver,
  IAny2EVMMessageReceiverInterface,
} from "../../../../../../../../lib/chainlink/contracts/src/v0.8/shared/interfaces/IAny2EVMMessageReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "ccipReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAny2EVMMessageReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IAny2EVMMessageReceiverInterface {
    return new Interface(_abi) as IAny2EVMMessageReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAny2EVMMessageReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAny2EVMMessageReceiver;
  }
}
