/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustodianNavReporter } from "./CustodianNavReporter";
export type { IReportableVault } from "./IReportableVault";
