/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ComplianceRegistryUpgradeable {
  export type PolicyStruct = {
    allowUS: boolean;
    allowEU: boolean;
    allowSG: boolean;
    allowUK: boolean;
    regD506c: boolean;
    regS: boolean;
    micaART: boolean;
    micaEMT: boolean;
    proOnly: boolean;
    travelRuleRequired: boolean;
  };

  export type PolicyStructOutput = [
    allowUS: boolean,
    allowEU: boolean,
    allowSG: boolean,
    allowUK: boolean,
    regD506c: boolean,
    regS: boolean,
    micaART: boolean,
    micaEMT: boolean,
    proOnly: boolean,
    travelRuleRequired: boolean
  ] & {
    allowUS: boolean;
    allowEU: boolean;
    allowSG: boolean;
    allowUK: boolean;
    regD506c: boolean;
    regS: boolean;
    micaART: boolean;
    micaEMT: boolean;
    proOnly: boolean;
    travelRuleRequired: boolean;
  };

  export type ProfileStruct = {
    kyc: boolean;
    accredited: boolean;
    kycAsOf: BigNumberish;
    kycExpiry: BigNumberish;
    isoCountry: BytesLike;
    frozen: boolean;
  };

  export type ProfileStructOutput = [
    kyc: boolean,
    accredited: boolean,
    kycAsOf: bigint,
    kycExpiry: bigint,
    isoCountry: string,
    frozen: boolean
  ] & {
    kyc: boolean;
    accredited: boolean;
    kycAsOf: bigint;
    kycExpiry: bigint;
    isoCountry: string;
    frozen: boolean;
  };
}

export interface ComplianceRegistryUpgradeableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "ATTESTOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "allowlist"
      | "canHold"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "policies"
      | "profiles"
      | "proxiableUUID"
      | "renounceRole"
      | "revokeRole"
      | "setAllowlist"
      | "setPolicy"
      | "setProfile"
      | "supportsInterface"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowlistSet"
      | "Initialized"
      | "PolicySet"
      | "ProfileSet"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ATTESTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowlist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canHold",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "policies", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowlist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [BytesLike, ComplianceRegistryUpgradeable.PolicyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setProfile",
    values: [AddressLike, ComplianceRegistryUpgradeable.ProfileStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ATTESTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowlist", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canHold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AllowlistSetEvent {
  export type InputTuple = [user: AddressLike, ok: boolean];
  export type OutputTuple = [user: string, ok: boolean];
  export interface OutputObject {
    user: string;
    ok: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicySetEvent {
  export type InputTuple = [
    id: BytesLike,
    p: ComplianceRegistryUpgradeable.PolicyStruct
  ];
  export type OutputTuple = [
    id: string,
    p: ComplianceRegistryUpgradeable.PolicyStructOutput
  ];
  export interface OutputObject {
    id: string;
    p: ComplianceRegistryUpgradeable.PolicyStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileSetEvent {
  export type InputTuple = [
    user: AddressLike,
    prof: ComplianceRegistryUpgradeable.ProfileStruct
  ];
  export type OutputTuple = [
    user: string,
    prof: ComplianceRegistryUpgradeable.ProfileStructOutput
  ];
  export interface OutputObject {
    user: string;
    prof: ComplianceRegistryUpgradeable.ProfileStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceRegistryUpgradeable extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceRegistryUpgradeable;
  waitForDeployment(): Promise<this>;

  interface: ComplianceRegistryUpgradeableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ATTESTOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  allowlist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  canHold: TypedContractMethod<
    [user: AddressLike, policyId: BytesLike],
    [boolean],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  policies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        allowUS: boolean;
        allowEU: boolean;
        allowSG: boolean;
        allowUK: boolean;
        regD506c: boolean;
        regS: boolean;
        micaART: boolean;
        micaEMT: boolean;
        proOnly: boolean;
        travelRuleRequired: boolean;
      }
    ],
    "view"
  >;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, string, boolean] & {
        kyc: boolean;
        accredited: boolean;
        kycAsOf: bigint;
        kycExpiry: bigint;
        isoCountry: string;
        frozen: boolean;
      }
    ],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAllowlist: TypedContractMethod<
    [user: AddressLike, ok: boolean],
    [void],
    "nonpayable"
  >;

  setPolicy: TypedContractMethod<
    [id: BytesLike, p: ComplianceRegistryUpgradeable.PolicyStruct],
    [void],
    "nonpayable"
  >;

  setProfile: TypedContractMethod<
    [user: AddressLike, prof: ComplianceRegistryUpgradeable.ProfileStruct],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ATTESTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowlist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canHold"
  ): TypedContractMethod<
    [user: AddressLike, policyId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        allowUS: boolean;
        allowEU: boolean;
        allowSG: boolean;
        allowUK: boolean;
        regD506c: boolean;
        regS: boolean;
        micaART: boolean;
        micaEMT: boolean;
        proOnly: boolean;
        travelRuleRequired: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, string, boolean] & {
        kyc: boolean;
        accredited: boolean;
        kycAsOf: bigint;
        kycExpiry: bigint;
        isoCountry: string;
        frozen: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowlist"
  ): TypedContractMethod<
    [user: AddressLike, ok: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [id: BytesLike, p: ComplianceRegistryUpgradeable.PolicyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProfile"
  ): TypedContractMethod<
    [user: AddressLike, prof: ComplianceRegistryUpgradeable.ProfileStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AllowlistSet"
  ): TypedContractEvent<
    AllowlistSetEvent.InputTuple,
    AllowlistSetEvent.OutputTuple,
    AllowlistSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "PolicySet"
  ): TypedContractEvent<
    PolicySetEvent.InputTuple,
    PolicySetEvent.OutputTuple,
    PolicySetEvent.OutputObject
  >;
  getEvent(
    key: "ProfileSet"
  ): TypedContractEvent<
    ProfileSetEvent.InputTuple,
    ProfileSetEvent.OutputTuple,
    ProfileSetEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AllowlistSet(address,bool)": TypedContractEvent<
      AllowlistSetEvent.InputTuple,
      AllowlistSetEvent.OutputTuple,
      AllowlistSetEvent.OutputObject
    >;
    AllowlistSet: TypedContractEvent<
      AllowlistSetEvent.InputTuple,
      AllowlistSetEvent.OutputTuple,
      AllowlistSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "PolicySet(bytes32,tuple)": TypedContractEvent<
      PolicySetEvent.InputTuple,
      PolicySetEvent.OutputTuple,
      PolicySetEvent.OutputObject
    >;
    PolicySet: TypedContractEvent<
      PolicySetEvent.InputTuple,
      PolicySetEvent.OutputTuple,
      PolicySetEvent.OutputObject
    >;

    "ProfileSet(address,tuple)": TypedContractEvent<
      ProfileSetEvent.InputTuple,
      ProfileSetEvent.OutputTuple,
      ProfileSetEvent.OutputObject
    >;
    ProfileSet: TypedContractEvent<
      ProfileSetEvent.InputTuple,
      ProfileSetEvent.OutputTuple,
      ProfileSetEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
