/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  StableErrors,
  StableErrorsInterface,
} from "../../../../contracts/stable/common/StableErrors";

const _abi = [
  {
    inputs: [],
    name: "CollateralTypeNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "ComplianceBlocked",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAuthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "Paused",
    type: "error",
  },
  {
    inputs: [],
    name: "ReserveRatioBreach",
    type: "error",
  },
  {
    inputs: [],
    name: "SafeCheckFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "StaleOracle",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212201c484935d0f5d4af1dc344304bb8965e0f4974178f407f4b2793d600e4431fb464736f6c63430008180033";

type StableErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StableErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StableErrors__factory extends ContractFactory {
  constructor(...args: StableErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      StableErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StableErrors__factory {
    return super.connect(runner) as StableErrors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StableErrorsInterface {
    return new Interface(_abi) as StableErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StableErrors {
    return new Contract(address, _abi, runner) as unknown as StableErrors;
  }
}
