/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface ISO20022EmitterInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "ISO20022Camt053" | "ISO20022Pacs009"
  ): EventFragment;
}

export namespace ISO20022Camt053Event {
  export type InputTuple = [
    stmtHash: BytesLike,
    uri: string,
    asOfTs: BigNumberish
  ];
  export type OutputTuple = [stmtHash: string, uri: string, asOfTs: bigint];
  export interface OutputObject {
    stmtHash: string;
    uri: string;
    asOfTs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ISO20022Pacs009Event {
  export type InputTuple = [
    docHash: BytesLike,
    uri: string,
    msgId: BigNumberish,
    txnTs: BigNumberish,
    participantLEI: BytesLike
  ];
  export type OutputTuple = [
    docHash: string,
    uri: string,
    msgId: bigint,
    txnTs: bigint,
    participantLEI: string
  ];
  export interface OutputObject {
    docHash: string;
    uri: string;
    msgId: bigint;
    txnTs: bigint;
    participantLEI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISO20022Emitter extends BaseContract {
  connect(runner?: ContractRunner | null): ISO20022Emitter;
  waitForDeployment(): Promise<this>;

  interface: ISO20022EmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ISO20022Camt053"
  ): TypedContractEvent<
    ISO20022Camt053Event.InputTuple,
    ISO20022Camt053Event.OutputTuple,
    ISO20022Camt053Event.OutputObject
  >;
  getEvent(
    key: "ISO20022Pacs009"
  ): TypedContractEvent<
    ISO20022Pacs009Event.InputTuple,
    ISO20022Pacs009Event.OutputTuple,
    ISO20022Pacs009Event.OutputObject
  >;

  filters: {
    "ISO20022Camt053(bytes32,string,uint64)": TypedContractEvent<
      ISO20022Camt053Event.InputTuple,
      ISO20022Camt053Event.OutputTuple,
      ISO20022Camt053Event.OutputObject
    >;
    ISO20022Camt053: TypedContractEvent<
      ISO20022Camt053Event.InputTuple,
      ISO20022Camt053Event.OutputTuple,
      ISO20022Camt053Event.OutputObject
    >;

    "ISO20022Pacs009(bytes32,string,uint64,uint64,bytes32)": TypedContractEvent<
      ISO20022Pacs009Event.InputTuple,
      ISO20022Pacs009Event.OutputTuple,
      ISO20022Pacs009Event.OutputObject
    >;
    ISO20022Pacs009: TypedContractEvent<
      ISO20022Pacs009Event.InputTuple,
      ISO20022Pacs009Event.OutputTuple,
      ISO20022Pacs009Event.OutputObject
    >;
  };
}
