/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProofOfReserves,
  IProofOfReservesInterface,
} from "../../../contracts/interfaces/IProofOfReserves";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "reserveId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkMint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "reserveId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkRedeem",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProofOfReserves__factory {
  static readonly abi = _abi;
  static createInterface(): IProofOfReservesInterface {
    return new Interface(_abi) as IProofOfReservesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProofOfReserves {
    return new Contract(address, _abi, runner) as unknown as IProofOfReserves;
  }
}
