/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  PriceOracleMock,
  PriceOracleMockInterface,
} from "../../../../contracts/stable/mocks/PriceOracleMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "priceE18",
    outputs: [
      {
        internalType: "uint256",
        name: "p",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "ts",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "p",
        type: "uint256",
      },
    ],
    name: "set",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061018c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633825d828146100465780633a697cad14610072578063aea91078146100c0575b600080fd5b61007061005436600461010a565b6001600160a01b03909116600090815260208190526040902055565b005b61009d610080366004610134565b6001600160a01b0316600090815260208190526040902054904290565b6040805192835267ffffffffffffffff9091166020830152015b60405180910390f35b6100e06100ce366004610134565b60006020819052908152604090205481565b6040519081526020016100b7565b80356001600160a01b038116811461010557600080fd5b919050565b6000806040838503121561011d57600080fd5b610126836100ee565b946020939093013593505050565b60006020828403121561014657600080fd5b61014f826100ee565b939250505056fea2646970667358221220e43cc22c38cd851fb4a8d58c514668abac110bec4cb053878cf44c6a1cfe37ed64736f6c63430008180033";

type PriceOracleMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PriceOracleMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PriceOracleMock__factory extends ContractFactory {
  constructor(...args: PriceOracleMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PriceOracleMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PriceOracleMock__factory {
    return super.connect(runner) as PriceOracleMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PriceOracleMockInterface {
    return new Interface(_abi) as PriceOracleMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PriceOracleMock {
    return new Contract(address, _abi, runner) as unknown as PriceOracleMock;
  }
}
