/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace Client {
  export type EVMTokenAmountStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type EVMTokenAmountStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type EVM2AnyMessageStruct = {
    receiver: BytesLike;
    data: BytesLike;
    tokenAmounts: Client.EVMTokenAmountStruct[];
    feeToken: AddressLike;
    extraArgs: BytesLike;
  };

  export type EVM2AnyMessageStructOutput = [
    receiver: string,
    data: string,
    tokenAmounts: Client.EVMTokenAmountStructOutput[],
    feeToken: string,
    extraArgs: string
  ] & {
    receiver: string;
    data: string;
    tokenAmounts: Client.EVMTokenAmountStructOutput[];
    feeToken: string;
    extraArgs: string;
  };
}

export interface MockRouterClientInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ccipSend"
      | "getFee"
      | "isChainSupported"
      | "isOfframp"
      | "lastChainSelector"
      | "lastMessage"
      | "lastMessageId"
      | "quotedFee"
      | "setFee"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Sent"): EventFragment;

  encodeFunctionData(
    functionFragment: "ccipSend",
    values: [BigNumberish, Client.EVM2AnyMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [BigNumberish, Client.EVM2AnyMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOfframp",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastChainSelector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastMessageId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "quotedFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ccipSend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOfframp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastChainSelector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMessageId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quotedFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
}

export namespace SentEvent {
  export type InputTuple = [
    id: BytesLike,
    chain: BigNumberish,
    receiver: AddressLike
  ];
  export type OutputTuple = [id: string, chain: bigint, receiver: string];
  export interface OutputObject {
    id: string;
    chain: bigint;
    receiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockRouterClient extends BaseContract {
  connect(runner?: ContractRunner | null): MockRouterClient;
  waitForDeployment(): Promise<this>;

  interface: MockRouterClientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ccipSend: TypedContractMethod<
    [
      destinationChainSelector: BigNumberish,
      message: Client.EVM2AnyMessageStruct
    ],
    [string],
    "payable"
  >;

  getFee: TypedContractMethod<
    [arg0: BigNumberish, arg1: Client.EVM2AnyMessageStruct],
    [bigint],
    "view"
  >;

  isChainSupported: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  isOfframp: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  lastChainSelector: TypedContractMethod<[], [bigint], "view">;

  lastMessage: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        receiver: string;
        data: string;
        feeToken: string;
        extraArgs: string;
      }
    ],
    "view"
  >;

  lastMessageId: TypedContractMethod<[], [string], "view">;

  quotedFee: TypedContractMethod<[], [bigint], "view">;

  setFee: TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ccipSend"
  ): TypedContractMethod<
    [
      destinationChainSelector: BigNumberish,
      message: Client.EVM2AnyMessageStruct
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: Client.EVM2AnyMessageStruct],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isChainSupported"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOfframp"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastChainSelector"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastMessage"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        receiver: string;
        data: string;
        feeToken: string;
        extraArgs: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastMessageId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quotedFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[fee: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Sent"
  ): TypedContractEvent<
    SentEvent.InputTuple,
    SentEvent.OutputTuple,
    SentEvent.OutputObject
  >;

  filters: {
    "Sent(bytes32,uint64,address)": TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
    Sent: TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
  };
}
