/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface ISO20022EventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "CAMT_Statement"
      | "PACS_008_Payment"
      | "SEC_Mint"
      | "SEC_Redeem"
  ): EventFragment;
}

export namespace CAMT_StatementEvent {
  export type InputTuple = [
    accountId: BytesLike,
    delta: BigNumberish,
    newBalance: BigNumberish,
    statementRef: string,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    accountId: string,
    delta: bigint,
    newBalance: bigint,
    statementRef: string,
    ts: bigint
  ];
  export interface OutputObject {
    accountId: string;
    delta: bigint;
    newBalance: bigint;
    statementRef: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PACS_008_PaymentEvent {
  export type InputTuple = [
    payer: AddressLike,
    payee: AddressLike,
    messageId: BytesLike,
    amount: BigNumberish,
    currencyToken: AddressLike,
    valueDate: BigNumberish,
    debtorIban: string,
    creditorIban: string,
    purposeCode: string
  ];
  export type OutputTuple = [
    payer: string,
    payee: string,
    messageId: string,
    amount: bigint,
    currencyToken: string,
    valueDate: bigint,
    debtorIban: string,
    creditorIban: string,
    purposeCode: string
  ];
  export interface OutputObject {
    payer: string;
    payee: string;
    messageId: string;
    amount: bigint;
    currencyToken: string;
    valueDate: bigint;
    debtorIban: string;
    creditorIban: string;
    purposeCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SEC_MintEvent {
  export type InputTuple = [
    instrumentId: BytesLike,
    subscriber: AddressLike,
    grossPaid: BigNumberish,
    feeBps: BigNumberish,
    sharesOut: BigNumberish,
    nonce: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    instrumentId: string,
    subscriber: string,
    grossPaid: bigint,
    feeBps: bigint,
    sharesOut: bigint,
    nonce: string,
    ts: bigint
  ];
  export interface OutputObject {
    instrumentId: string;
    subscriber: string;
    grossPaid: bigint;
    feeBps: bigint;
    sharesOut: bigint;
    nonce: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SEC_RedeemEvent {
  export type InputTuple = [
    instrumentId: BytesLike,
    redeemer: AddressLike,
    sharesIn: BigNumberish,
    feeBps: BigNumberish,
    netPayout: BigNumberish,
    nonce: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    instrumentId: string,
    redeemer: string,
    sharesIn: bigint,
    feeBps: bigint,
    netPayout: bigint,
    nonce: string,
    ts: bigint
  ];
  export interface OutputObject {
    instrumentId: string;
    redeemer: string;
    sharesIn: bigint;
    feeBps: bigint;
    netPayout: bigint;
    nonce: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISO20022Events extends BaseContract {
  connect(runner?: ContractRunner | null): ISO20022Events;
  waitForDeployment(): Promise<this>;

  interface: ISO20022EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "CAMT_Statement"
  ): TypedContractEvent<
    CAMT_StatementEvent.InputTuple,
    CAMT_StatementEvent.OutputTuple,
    CAMT_StatementEvent.OutputObject
  >;
  getEvent(
    key: "PACS_008_Payment"
  ): TypedContractEvent<
    PACS_008_PaymentEvent.InputTuple,
    PACS_008_PaymentEvent.OutputTuple,
    PACS_008_PaymentEvent.OutputObject
  >;
  getEvent(
    key: "SEC_Mint"
  ): TypedContractEvent<
    SEC_MintEvent.InputTuple,
    SEC_MintEvent.OutputTuple,
    SEC_MintEvent.OutputObject
  >;
  getEvent(
    key: "SEC_Redeem"
  ): TypedContractEvent<
    SEC_RedeemEvent.InputTuple,
    SEC_RedeemEvent.OutputTuple,
    SEC_RedeemEvent.OutputObject
  >;

  filters: {
    "CAMT_Statement(bytes32,int256,uint256,string,uint64)": TypedContractEvent<
      CAMT_StatementEvent.InputTuple,
      CAMT_StatementEvent.OutputTuple,
      CAMT_StatementEvent.OutputObject
    >;
    CAMT_Statement: TypedContractEvent<
      CAMT_StatementEvent.InputTuple,
      CAMT_StatementEvent.OutputTuple,
      CAMT_StatementEvent.OutputObject
    >;

    "PACS_008_Payment(address,address,bytes32,uint256,address,uint64,string,string,string)": TypedContractEvent<
      PACS_008_PaymentEvent.InputTuple,
      PACS_008_PaymentEvent.OutputTuple,
      PACS_008_PaymentEvent.OutputObject
    >;
    PACS_008_Payment: TypedContractEvent<
      PACS_008_PaymentEvent.InputTuple,
      PACS_008_PaymentEvent.OutputTuple,
      PACS_008_PaymentEvent.OutputObject
    >;

    "SEC_Mint(bytes32,address,uint256,uint16,uint256,bytes32,uint64)": TypedContractEvent<
      SEC_MintEvent.InputTuple,
      SEC_MintEvent.OutputTuple,
      SEC_MintEvent.OutputObject
    >;
    SEC_Mint: TypedContractEvent<
      SEC_MintEvent.InputTuple,
      SEC_MintEvent.OutputTuple,
      SEC_MintEvent.OutputObject
    >;

    "SEC_Redeem(bytes32,address,uint256,uint16,uint256,bytes32,uint64)": TypedContractEvent<
      SEC_RedeemEvent.InputTuple,
      SEC_RedeemEvent.OutputTuple,
      SEC_RedeemEvent.OutputObject
    >;
    SEC_Redeem: TypedContractEvent<
      SEC_RedeemEvent.InputTuple,
      SEC_RedeemEvent.OutputTuple,
      SEC_RedeemEvent.OutputObject
    >;
  };
}
