/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockComplianceRegistry } from "./MockComplianceRegistry";
export type { MockMintableERC20 } from "./MockMintableERC20";
